"""Generates src/server/exports_gen.cpp and src/server/hl.def from the original
Cry of Fear server DLL's export list (src/server/hl_exports.txt, from dumpbin /exports).

Every export becomes a jump thunk into hl_cof.dll. Many export names are C++
decorated names containing '?' and '@', which the MSVC linker refuses to write
(it cuts them at the first '@'). So they are exported under same-length
placeholder names ('?' -> 'Q', '@' -> 'Z') listed in src/server/hl_export_map.txt,
and test/fix_exports.py patches the real names into the built DLL.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
names = [n for n in open(os.path.join(ROOT, 'src', 'server', 'hl_exports.txt')).read().split() if n]
wrapped = {'GiveFnptrsToDll', 'GetEntityAPI', 'GetEntityAPI2'}
fwd = [n for n in names if n not in wrapped]
mapping = []

with open(os.path.join(ROOT, 'src', 'server', 'exports_gen.cpp'), 'w', newline='\r\n') as f:
    f.write('// GENERATED by test/gen_server_exports.py from the original hl.dll export list. Do not edit.\n')
    f.write('// One jump thunk per export of the original Cry of Fear server DLL (hl_cof.dll).\n\n')
    f.write('extern "C" void FpServer_EnsureLoaded(void);\n\n')
    f.write(f'extern "C" const int g_numExports = {len(fwd)};\n')
    f.write('extern "C" const char *const g_exportNames[] = {\n')
    for n in fwd:
        f.write(f'\t"{n}",\n')
    f.write('};\n')
    f.write(f'extern "C" void *g_exportPtrs[{len(fwd)}];\n')
    f.write(f'void *g_exportPtrs[{len(fwd)}];\n\n')
    for i, n in enumerate(fwd):
        f.write(f'extern "C" __declspec(naked) void S_{i}(void) {{ __asm pushad __asm call FpServer_EnsureLoaded '
                f'__asm popad __asm jmp dword ptr [g_exportPtrs + {i * 4}] }}\n')
        placeholder = n.replace('?', 'Q').replace('@', 'Z')
        mapping.append((placeholder, n))
        f.write(f'#pragma comment(linker, "/EXPORT:{placeholder}=_S_{i}")\n')

with open(os.path.join(ROOT, 'src', 'server', 'hl.def'), 'w', newline='\r\n') as f:
    f.write('LIBRARY hl\nEXPORTS\n')
    f.write('\tGiveFnptrsToDll=W_GiveFnptrsToDll\n\tGetEntityAPI=W_GetEntityAPI\n\tGetEntityAPI2=W_GetEntityAPI2\n')

placeholders = [p for p, _ in mapping]
assert len(set(placeholders)) == len(placeholders), 'placeholder names collide'
with open(os.path.join(ROOT, 'src', 'server', 'hl_export_map.txt'), 'w') as f:
    for p, n in mapping:
        if p != n:
            f.write(f'{p} {n}\n')
print('forwarded', len(fwd), 'wrapped', len(wrapped & set(names)), 'renamed later', sum(p != n for p, n in mapping))
